// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.1385b237-0f28-495e-a260-0b63a9f63bb7";
        public const string Name = "Insert Guid";
        public const string Description = @"Allows for insertion of a guid into the currently open file in the editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mensur Islami";
        public const string Tags = "";
    }
}
